# Generated by Django 4.2.15 on 2024-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_manager', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
